### ISSUE TITLE
Error 500s on map tiles

### ISSUE THREAD

**Issue by MortenHofft** [gbif/maps#13]
We get a lot of error 500s on [maps with geometry queries](https://demo.gbif.org/occurrence/map?geometry=POLYGON%20((57.65624999999999%2070.37785394109224,%2011.25%2011.178401873711785,%2060.46875%202.1088986592431382,%2061.17187499999999%2051.6180165487737,%2042.1875%2037.16031654673677,%2057.65624999999999%2070.37785394109224))&geometry=POLYGON%20((97.734375%2037.71859032558816,%2097.734375%2058.81374171570782,%20129.375%2058.81374171570782,%20129.375%2037.71859032558816,%2097.734375%2037.71859032558816))&geometry=POLYGON%20((13.359375%2065.6582745198266,%200%2060.930432202923335,%2014.765625%2058.07787626787517,%2013.359375%2065.6582745198266))&has_coordinate=true&has_geospatial_issue=false). It works fine, but half the tiles return 500.

It isn't clear why [one tile fails](http://c-api.gbif-uat.org/v2/map/occurrence/adhoc/3/7/5.png?srs=EPSG:4326&style=classic.poly&bin=hex&hexPerTile=17&advanced=false&geometry=POLYGON+((57.65624999999999+70.37785394109224,+11.25+11.178401873711785,+60.46875+2.1088986592431382,+61.17187499999999+51.6180165487737,+42.1875+37.16031654673677,+57.65624999999999+70.37785394109224))&geometry=POLYGON+((97.734375+37.71859032558816,+97.734375+58.81374171570782,+129.375+58.81374171570782,+129.375+37.71859032558816,+97.734375+37.71859032558816))&geometry=POLYGON+((13.359375+65.6582745198266,+0+60.930432202923335,+14.765625+58.07787626787517,+13.359375+65.6582745198266))&hasCoordinate=true&hasGeospatialIssue=false&locale=en&repatriated=) and [another works](http://c-api.gbif-uat.org/v2/map/occurrence/adhoc/3/5/3.png?srs=EPSG:4326&style=classic.poly&bin=hex&hexPerTile=17&advanced=false&geometry=POLYGON+((57.65624999999999+70.37785394109224,+11.25+11.178401873711785,+60.46875+2.1088986592431382,+61.17187499999999+51.6180165487737,+42.1875+37.16031654673677,+57.65624999999999+70.37785394109224))&geometry=POLYGON+((97.734375+37.71859032558816,+97.734375+58.81374171570782,+129.375+58.81374171570782,+129.375+37.71859032558816,+97.734375+37.71859032558816))&geometry=POLYGON+((13.359375+65.6582745198266,+0+60.930432202923335,+14.765625+58.07787626787517,+13.359375+65.6582745198266))&hasCoordinate=true&locale=en&repatriated=) . I might be as simple as empty tiles not returning 204?

**Comment by MortenHofft** [comment]
Seems to be the hexagon binning that fails when geometric queries are involved:

**with binning**
http://api.gbif-uat.org/v2/map/occurrence/adhoc/3/6/3.png?srs=EPSG:4326&style=classic.poly&geometry=POLYGON%20((40%2040,%2020%2045,%2045%2030,%2040%2040))

**Fails with bininng**
http://api.gbif-uat.org/v2/map/occurrence/adhoc/3/6/3.png?srs=EPSG:4326&style=classic.poly&geometry=POLYGON%20((40%2040,%2020%2045,%2045%2030,%2040%2040))&bin=hex&hexPerTile=17

**Comment by timrobertson100** [comment]
Appears to be incorrectly giving 500s when there is no content
