### ISSUE TITLE
Improve capabilities response

### ISSUE THREAD

**Issue by timrobertson100** [gbif/maps#17]
We believe there are examples where the capabilities is providing an extent smaller than the actual range.  Wild speculation is that this will be a rounding error since we use Z0 to determine the extent, but that is course.  The solution should be to always clip to the lat/lng larger than the true range.
(`/dataset/271c444f-f8d8-4986-b748-e7367755c0c1` is a known example)

It would be good if some records covering the dateline only resulted in the map zooming to the location, rather than staying at world zoom.  How this could be implemented robustly needs some consideration (e.g. 170 -> 190 or should it be -190 -> -170 or 170 -> -170 etc).  OpenLayers would allow `map.setExtent([-250, -10, -100, 10])` for example.

**Comment by MattBlissett** [comment]
Implemented after the bug reported in #46.
