### ISSUE TITLE
Add service registry and proper GBIF configuration to the vectortile-server

### ISSUE THREAD

**Issue by timrobertson100** [gbif/maps#2]
The ```vectortile-server``` is a Dropwizard based application.

This needs to include the necessary parts for service registration in Zookeeper to be managed as part of the typical deployment across environments, and the configuration should be moved to github.com/gbif/gbif-configuration.

@fmendezh - do you have any examples of a DW project using the ZK service registration?

**Comment by fmendezh** [comment]
Please refer to these classes: https://github.com/gbif/gbif-microservice/blob/master/src/main/java/org/gbif/jetty/ServerFactory.java#L54
https://github.com/gbif/gbif-microservice/blob/master/src/main/java/org/gbif/ws/discovery/lifecycle/DiscoveryLifeCycle.java  in Dropwizard there's something similar called the Managed interface:
public class ZKDiscoveryClient implements Managed {

    private final Client client;

    public OrchestrateClientManager(final Client client) {
        this.client = client;
    }

    @Override
    public void start() throws Exception {
        // nothing to do here
    }

    @Override
    public void stop() throws Exception {
        client.close();
    }

}

**Comment by MattBlissett** [comment]
I've taken the code from gbif-microservice, and added it directly to this project.

I can pull it out into another project if we decided to stick with Dropwizard, and after checking it works with our deployment configuration.
