### ISSUE TITLE
Delete temporary files after loading into HBase

### ISSUE THREAD

**Issue by MattBlissett** [gbif/maps#21]
Files are left in HDFS /tmp:

```
/tmp/prod_d_maps_20170904_1200 (just two files)
/tmp/84faadd1-0289-4ab9-bed5-2d6e85d5348a (>6000 files)
```

HDFS gets very cranky when there are millions of files — and I just deleted 2.9 million.

**Comment by timrobertson100** [comment]
Looks like it is the `SnapshotInputFormat` that is creating the '/tmp/84faadd1-0289-4ab9-bed5-2d6e85d5348a' as it's restore directory.  We should set the restore directory manually to be a sub directory of the current run (e.g. ´/tmp/prod_d_maps_20170904_1200/restore´) and then at the end simply delete the current run folder.
