### ISSUE TITLE
Raster pixel tiles from points source don't render exactly correctly

### ISSUE THREAD

**Issue by MattBlissett** [gbif/maps#22]
(Raster pixel tiles from tile sources are unaffected, so this is related to the different vector tile sizes produced when the source is points vs tiles.)

Live images embedded here.

First, square bins of size 8, which is one pixel when scaled to a 512px tile:

![First](https://api.gbif.org/v2/map/occurrence/density/5/15/9@1x.png?style=purpleYellow-noborder.poly&bin=square&squareSize=8&taxonKey=2436940&srs=EPSG%3A3857)

Second, points -- they are not all exactly one pixel:

![Second](https://api.gbif.org/v2/map/occurrence/density/5/15/9@1x.png?style=purpleYellow.point&taxonKey=2436940&srs=EPSG%3A3857)

Third, tile source with points which looks  fine:

![Third](https://api.gbif.org/v2/map/occurrence/density/5/15/9@1x.png?style=purpleYellow-noborder.poly&bin=square&squareSize=8&taxonKey=1&srs=EPSG%3A3857)

**Comment by MattBlissett** [comment]
Example: the species map here, with a pixel style set.

https://www.gbif.org/species/2436940

http://api.gbif.org/v1/map/?type=TAXON&key=2436940&resolution=1 -- the old one looks nicer (and correct) since the legacy API is directed to 8px binned squares.

**Comment by MattBlissett** [comment]
I've now fully understood this, and I'm not sure why I didn't see it earlier. Perhaps I was concentrating too much on the all occurrences view.

"Points" tiles (under 250000 occurrences in the filter) have extent 4096, and contain data accurate to the nearest integer.  If we render that perfectly onto a 4096px tile, and magnify a tiny area, we get something like this (purple) :

<img width="363" alt="4k tiles" src="https://user-images.githubusercontent.com/583320/30709101-5787b974-9f01-11e7-9891-5556f23d5685.png">

When we want that as 512px for display at standard resolution, we need to colour blocks of 8x8 pixels, i.e. the yellow square. There's no reasonable way to get opaque, correctly coloured 8x8px squares out of this data using a Mapnik stylesheet.

Instead, for sharp "pixel" tiles we should square bin the data with size 8 (4096/8=512), and render that with a polygon style. The binned vector tile is significantly smaller anyway.

However, for the pyramid tiles, which are often very dense, the binned vector tile is significantly larger and slower -- so we should use them where possible.

**Comment by timrobertson100** [comment]
Alternatively we add the ability to request 512px tiles in the VT server
which may be a more trivial change?

**Comment by timrobertson100** [comment]
https://github.com/gbif/maps/blob/master/vectortile-server/src/main/java/org/gbif/maps/resource/TileResource.java#L238

It's only the reference to that static value - we could pass in a param and
if missing use the default.

**Comment by MattBlissett** [comment]
Yes, that's reasonable. I'll do that.

I tried reading the extent of a tile in node-mapnik, but it always returns 4096. Inspecting the bytecode works, but just generating 512 extent tiles will be better.

**Comment by MattBlissett** [comment]
Fixed by generating vector tiles at 512 extent, was deployed on Friday.
