### ISSUE TITLE
maps not working on UAT

### ISSUE THREAD

**Issue by MortenHofft** [gbif/maps#25]
It is difficult to have confidence in a prod build of the website when there isn't a working test environment.

https://www.gbif-uat.org/country/ES/summary fx shows a page with no maps. I assume it would work in prod environment and cross my fingers.

**Comment by MortenHofft** [comment]
Perhaps we could create an environment where we could test a prod build with prod endpoints? Whatever the name of such an environment should be. "Staging"?

**Comment by MattBlissett** [comment]
UAT ought to work (we shouldn't leave it broken for this long), and within the next few weeks we will be setting up a process to automatically copy prod to UAT, perhaps once per week.

**Comment by MattBlissett** [comment]
I'm working on fixing the maps today.

The smaller maps are still working: https://www.gbif-uat.org/country/CD/summary

**Comment by MattBlissett** [comment]
The large maps are now working.
