### ISSUE TITLE
Set up nagios monitoring

### ISSUE THREAD

**Issue by timrobertson100** [gbif/maps#3]
Nagios should monitor the following:
1. A vector tile coming from HBase (`vectortile-server`)
2. A vector tile coming from SOLR (`vectortile-server`)
3. A PNG tile coming from Mapnik (`mapnik-server`)

**Comment by MattBlissett** [comment]
https://github.com/gbif/gbif-configuration/blob/master/environments/dev/monitoring.yml#L355

Vector tiles from HBase and SOLR are done to some extent — checking for a response, but it should perhaps check for content, or at least non-zero size.
