### ISSUE TITLE
Migrate spark-process to Spark2

### ISSUE THREAD

**Issue by fmendezh** [gbif/maps#34]
The spark job [Backfill.scala](../blob/master/spark-process/src/main/scala/org/gbif/maps/spark/Backfill.scala) was written for Spark 1.6. It was ,partially, migrated to Spark 2 in the [spark2](../tree/spark2) branch. However it needs to be executed from the Ooozie [workflow](../blob/spark2/oozie-workflow/src/main/resources/workflow.xml). Our current version of Oozie (4.1.0) does not support Spark2 action out-of-the-box but there are at least 2 options of how to make it work:

1. [https://docs.cloudera.com/HDPDocuments/HDP2/HDP-2.6.0/bk_spark-component-guide/content/ch_oozie-spark-action.html#spark-config-oozie-spark2](https://docs.cloudera.com/HDPDocuments/HDP2/HDP-2.6.0/bk_spark-component-guide/content/ch_oozie-spark-action.html#spark-config-oozie-spark2)

2. Execute the action from a shell action.

This task can be split into 2 major concerns:
 - [x]  Evaluate the feasibility of running Spark 2 job in Oozie 4.1.0
 - [ ]  Depending on the previous evaluation, migrate this project to Spark2

**Comment by timrobertson100** [comment]
Please also bring the spark2 branch up to date with Master

**Comment by fmendezh** [comment]
I've managed to have a very simple Oozie workflow with a spark2 action:

1. `
hdfs dfs -mkdir /user/oozie/share/lib/lib_<tst>/spark2/
`

2. `
hdfs dfs -put /opt/cloudera/parcels/SPARK2/lib/spark2/jars/*  /user/oozie/share/lib/lib_<ts>/spark2/
`

3. `
hdfs dfs -put /opt/cloudera/parcels/SPARK2/lib/spark2/python/lib/*  /user/oozie/share/lib/lib_<ts>/spark2/
`

4. Copy the spark 1 lib to the spark2 folder (it has the action definition and xsd)
`
hdfs dfs -cp /user/oozie/share/lib/lib_<ts>/spark/oozie-sharelib-spark-4.1.0-cdh5.12.1.jar /user/oozie/share/lib/lib_<ts>/spark2/ 
 `
5.  `
hdfs dfs -chown -R oozie:oozie /user/oozie/share/lib/lib_<ts>/spark2/ 
 `

6. `
oozie admin  -oozie http://oozieurl:11000/oozie/ -sharelibupdate
`


7. Confirm that spark2 is listed
`
oozie admin  -oozie http://oozieurl:11000/oozie/ -shareliblist
`

8. And finally the Spark action should like the next example:
```xm
<action name="spark2-pi">
   <spark xmlns="uri:oozie:spark-action:0.1">
     <job-tracker>${jobTracker}</job-tracker>
      <name-node>${nameNode}</name-node>
       <master>yarn-cluster</master>
       <name>SparkPi</name>
       <class>org.apache.spark.examples.SparkPi</class>
       <jar>spark-examples_2.11-2.3.0.cloudera2.jar</jar>
       <spark-opts>--executor-memory 2G --num-executors 2 --conf spark.yarn.historyServer.address=${historServerUrl} --conf spark.eventLog.dir=${historyServerSpark2LogDir} --conf spark.eventLog.enabled=true</spark-opts>
     <arg>6</arg>
   </spark>
   <ok to="end" />
  <error to="fail" />
</action>
```

8.  job.properties file for the example above:
`
oozie.use.system.libpath=true
oozie.launcher.mapreduce.user.classpath.first=true
oozie.wf.application.path=hdfs://path-to-workflow/
oozie.libpath=/path-to-workflow/lib/
oozie.launcher.mapreduce.task.classpath.user.precedence=true
`

9.  `spark-examples_2.11-2.3.0.cloudera2.jar` was copied into /path-to-workflow/lib/ in HDFS

Note: <ts> is the timestamp added to the sharedlib definition
