### ISSUE TITLE
capabilities.json returning bad bounding boxes

### ISSUE THREAD

**Issue by dfloer** [gbif/maps#46]
I've been doing some mapping with the GBIF API, and I have found some bounding boxes that contain bad data.

For example, this one returns MaxLng = 0, which goes all the way to Africa instead of ending somewhere around -154. This bounding box is also not tall enough, cutting off some occurrences on the southern tip of the island.
https://api.gbif.org/v2/map/occurrence/density/capabilities.json?taxonKey=2480528
```json
{"minLat":19,
"minLng":-160,
"maxLat":23,
"maxLng":0,
"minYear":1891,
"maxYear":2021,
"total":5883,
"generated":"2021-09-02T14:00Z"}
```
And this one returns MaxLng = 0 being the prime meridian. Or perhaps 0 is an error condition. Either way, the result probably shouldn't be 0 unless the bounding box does stop at the prime meridian. I'm sure there are other cases. 
https://api.gbif.org/v2/map/occurrence/density/capabilities.json?taxonKey=5228134
```json
{"minLat": -38, 
"minLng": -13,
"maxLat": -38,
"maxLng": 0,
"minYear": 1929,
"maxYear": 2012,
"total": 43,
"generated": "2021-09-02T14:00Z"}
```
In the second one, also note how the bounding box has zero area, due to a strange choice to cast to integers here:
https://github.com/gbif/maps/blob/7c8c7154abf829d96dc310d2fe45807d849509d0/vectortile-server/src/main/java/org/gbif/maps/resource/Capabilities.java#L76-L80

These issues make it very hard to use the API to programmatically generate maps, because the bounding boxes are sometimes nearly useless at actually determining bounding boxes for map tiles to request.

The coordinates should probably be returned in decimal degrees with two places of accuracy (~1km), and they should actually reflect an accurate bounding box of the tiles. They should also contain the range of the taxon while also not being overbroad and containing a lot of area that doesn't have occurrences.

For the first, this could be solved by making sure that the minimal bounding box is 1x1 degrees, even if it's still an integer, which shouldn't break anyone's code expecting integers. For the second, a better way to give the bounding box would be the coordinates of the top left and bottom right corners, which would allow it to cross the antimeridian properly.

**Comment by dfloer** [comment]
Oh awesome! Thanks a bunch.
Is this live for me to try out?

**Comment by MattBlissett** [comment]
Hi,

It's on our test system, for example [_Buteo solitarius_](https://www.gbif-uat.org/species/2480528) or [Fiji](https://www.gbif-uat.org/country/FJ/summary).  Note the test system contains less data, and sometimes different data.  It will probably be deployed to api.gbif.org later this week.

Note I've changed the response to overlap the antimeridian in the same way as we use in other APIs, which is for the eastern longitude (in the western hemisphere) to have a value >180°.

https://api.gbif-uat.org/v2/map/occurrence/density/capabilities.json?country=FJ

It's unfortunately not practical to provide 0.01° resolution, as to ensure a suitably fast response only the most-zoomed-out (level 0) tile is used to calculate the bounding box.  This has 180°/512 resolution, about 0.35°. 

May I ask what project you are working on?

Thanks,

**Comment by dfloer** [comment]
@MattBlissett I'm working on static map generation to be integrated into a Discord bot: https://github.com/dronefly-garden/dronefly
Idea is that people can get range maps from GBIF right in Discord.
