### ISSUE TITLE
Tile aggregations appear wrong in MVTs

### ISSUE THREAD

**Issue by timrobertson100** [gbif/maps#48]
When using `&year=2019,2019` it appears the tile pyramid aggregation is not working as expected. It may or may not be related to the `year` parameter but I've only noticed it when present. The attached file shows the issue - rename the file to html and zoom in slowly on France and data will appear.

[years-mvt.txt](https://github.com/gbif/maps/files/7617343/years-mvt.txt)

**Comment by MattBlissett** [comment]
I wonder if this relates to https://github.com/gbif/portal-feedback/issues/3728

**Comment by timrobertson100** [comment]
The video shows the issue direct from the vector tiles, and the effect is present when any year filter is used (even all years). While the video doesn't show it, comparing the tiles for a year filter covering all years and when no filter is used indicates the data is in the tiles, and the problem may lie with filtering out year data from the tile.  

https://user-images.githubusercontent.com/237221/144992441-9d648db1-d9d0-40c4-abb9-ae4f615830a8.mov

I suggest we start by exploring if we have adequate test coverage for filtering a tile by year when the data is indeed in the tile.

**Comment by timrobertson100** [comment]
Fixed in production
