### ISSUE TITLE
New color scheme for map on GBIF.org homepage

### ISSUE THREAD

**Issue by javiesgm** [gbif/maps#55]
New green color scheme

```
/*
 * GBIF green maps.
 */

#occurrence {
  [total <=     5] { polygon-fill: #509E2F;  }
  [total >     5][total <=    10] { polygon-fill: #63A946;  }
  [total >    10][total <=    50] { polygon-fill: #76B35D;  }
  [total >    50][total <=   100] { polygon-fill: #8ABE74;  }
  [total >   100][total <=   500] { polygon-fill: #9DC98A;  }
  [total >   500][total <=  1000] { polygon-fill: #C2DDB6;  }
  [total >  1000][total <=  5000] { polygon-fill: #D5E8CD;  }
  [total >  5000][total <= 10000] { polygon-fill: #EDF5EA;  }
  [total > 10000]                 { polygon-fill: #ffffff;  }
}
```

**Comment by timrobertson100** [comment]
Deployed on gbif-dev 
@MortenHofft can you please verify it looks correct?

https://api.gbif-dev.org/v2/map/occurrence/density/0/0/0@1x.png?srs=EPSG:3857&style=green.point

**Comment by MortenHofft** [comment]
I'm surprised by the amount of grey (when I insepct them they are in fact the html color `grey`) - that looks wrong.
The colors in green-dot.mss are these:
<img width="164" alt="Screenshot 2022-02-16 at 08 35 18" src="https://user-images.githubusercontent.com/6759267/154217576-01d4ca34-fbbc-4ece-9cd6-77bf5ac56bc5.png">

**Comment by timrobertson100** [comment]
I suspect that was bad cache, from an earlier deployment. I've flushed caches so can you please check again (ensure chrome caching off too)

If it is bad, please can you post an example?

**Comment by MortenHofft** [comment]
Still a lot of greys:
![0@2x-1](https://user-images.githubusercontent.com/6759267/154222269-a5b68573-30b4-4990-97ae-4191c0a0b292.png)



I believe the design mock was created as an overlay on `glacier` https://github.com/gbif/maps/blob/master/mapnik-server/src/main/node/cartocss/glacier-dot.mss

So perhaps that should be the starting point - that would look like below. And 

```
#occurrence {
  marker-width: 2;
  marker-line-width: 0;
  marker-allow-overlap: true;
  marker-fill: #206EFF;
  marker-comp-op: screen;

                 [total <=     5] { marker-fill: #509E2F;  }
  [total >     5][total <=    10] { marker-fill: #63A946;  }
  [total >    10][total <=    50] { marker-fill: #76B35D;  }
  [total >    50][total <=   100] { marker-fill: #8ABE74;  }
  [total >   100][total <=   500] { marker-fill: #9DC98A;  }
  [total >   500][total <=  1000] { marker-fill: #C2DDB6;  }
  [total >  1000][total <=  5000] { marker-fill: #D5E8CD;  }
  [total >  5000][total <= 10000] { marker-fill: #EDF5EA;  }
  [total > 10000]                 { marker-fill: #ffffff;  }

  [zoom >= 11] { marker-width:  3.95; }
  [zoom >= 12] { marker-width:  6.25; }
  [zoom >= 13] { marker-width:  9.88; }
  [zoom >= 14] { marker-width:  15.63; }
  [zoom >= 15] { marker-width:  24.71; }
}
```

If we use the same naming convention as for `glacier`, then I guess the style definition would be called `green-dot.mss` and the url parameter called `green.point` - (just as you have)

And then perhaps register it in https://github.com/gbif/maps/blob/master/mapnik-server/src/main/node/styles.js#L48 ?

**Comment by timrobertson100** [comment]
Bad deploy - fixed?

**Comment by MattBlissett** [comment]
(The glacier style is significantly slower than the normal point styles, we should avoid it for the primary maps.)

I've set the green.point style to a "hard pixel" style, which avoids semitransparency of the dots, which is why it was looking blurry. It's now like the classic/purpleYellow styles, i.e. pixel-perfect.

https://api.gbif-dev.org/v2/map/demo1.html

https://api.gbif-dev.org/v2/map/debug/ol/

**Comment by MattBlissett** [comment]
Also the polygon style: https://api.gbif-dev.org/v2/map/demo4.html / https://api.gbif-dev.org/v2/map/styles.html#green-white

**Comment by javiesgm** [comment]
Thank you all ;) 

Can we try another combination? 

I included another threshold for over 10000 to 100000, and this one goes from green to yellow.

Let me know If it makes any sense


/*

 * GBIF green-yellow maps.

 */




#occurrence {

                 [total <=     5] { polygon-fill: #467B31;  }

  [total >     5][total <=    10] { polygon-fill: #588740;  }

  [total >    10][total <=    50] { polygon-fill: #76B35D;  }

  [total >    50][total <=   100] { polygon-fill: #7B9E5D;  }

  [total >   100][total <=   500] { polygon-fill: #8FAA6D;  }

  [total >   500][total <=  1000] { polygon-fill: #A1B57D;  }

  [total >  1000][total <=  5000] { polygon-fill: #B5C28F;  }

  [total >  5000][total <= 10000] { polygon-fill: #CACEA1;  }

  [total >  10000][total <= 100000] { polygon-fill: #DFDAB2;  }

  [total > 100000]                 { polygon-fill: #F4E7C5;  }

}

**Comment by MattBlissett** [comment]
I have deployed the test green style to UAT, since there isn't really enough data on dev to show it: 

https://api.gbif-uat.org/v2/map/demo1.html

https://api.gbif-uat.org/v2/map/demo4.html
