### ISSUE TITLE
Scheduled Map Builds in K8

### ISSUE THREAD

**Issue by fmendezh** [gbif/maps#71]
Modify Map Builds to match HBase and Hadoop versions supported by the Stackable/K8 cluster.
Propose and implement a mechanism to periodically scheduled these jobs.

**Comment by zaultooz** [comment]
The job is scheduled in Airflow described in the following two DAGs: https://github.com/gbif/stackable/blob/master/DAGs/dag-files/gbif-map-tiles-builder-spark.py and https://github.com/gbif/stackable/blob/master/DAGs/dag-files/gbif-map-points-builder-spark.py. They are currently separated into two jobs (one for points and one for map tiles) to allow turning of the scheduler independently. 

The code changes are located on the feature/stackable-hadoop-3-test branch in the maps repository.
